### ISSUE TITLE
Use OrderedDict to maintain roder of keys

### ISSUE THREAD

**Issue by mythreal** [chfw/pyexcel#10]
This is not so much an issue as it is a question for the Devs. Im new to Github and could not see another way to ask these questions. Please forgive me if this is improper use. 

Use OrderedDict to maintain oder of keys when saving sheet. Is it possible? 

As a side question I believe the license of your software Pyexcel is New BSD. What if anything would I have to do to satisfy those requirements to use your product in my software? Is I understand it, I would have to include the New BSD license in the application and the ReadMe file? Is their anything else that I need to do to fill any requirements you might have.

Thank you

**Comment by chfw** [comment]
Yes, it is possible. Here is more information about [BSD 3-clause license](http://opensource.org/licenses/BSD-3-Clause). As long as you satisfy those 3 clauses, you are free to use, modify and re-distribute pyexcel even in a proprietry software package.

**Comment by chfw** [comment]
Will implement it in v0.1.5 release.
