### ISSUE TITLE
Line termination for CSV output incorrect/can not be set

### ISSUE THREAD

**Issue by mvdw** [chfw/pyexcel#17]
I tried the following code to convert a ods with python 2.7:

```python
import pyexcel as pe
import pyexcel.ext.ods3
pyexcel.save_as(file_name=args.source, dest_file_name=args.destination)
```

The result has the following problem:

The result has the windows style line termination CR LF. I would expect that the result follows the system default. I understand that this is a problem with the csv module, but there you can set the "lineterminator" - it would be good to allow that here, too, and document this feature.

**Comment by chfw** [comment]
You can pass 'lineterminator' to csv module like the following:

    pyexcel.save_as(file_name=args.source, dest_file_name=args.destination,
                               dest_lineterminator='\n') # <--

**Comment by mvdw** [comment]
I tried it before with lineterminator='\n', which of course did not work.
Where is this documented? I did not find it.

**Comment by chfw** [comment]
Not clearly documented, to be honest. Will document it when I find the time.

**Comment by mvdw** [comment]
Thanks!
