### ISSUE TITLE
no sheet can have more than 26 columns in a xls file

### ISSUE THREAD

**Issue by bigbagboom** [chfw/pyexcel#4]
if one xls file has more than 26 columns in a sheet, the data from column 'AA' will be lost when I use function load() and save_as()

sample code:

import pyexcel as pe
import pyexcel.ext.xls # import it to be able handle xls file
import pyexcel.ext.xlsx # xlsx fi

book=pe.load('test1.xls')
book.save_as("test1.xlsx")  

book2=pe.load('test2.xls')
book2.save_as("test2.xlsx")

**Comment by chfw** [comment]
Yes, this is a bug. I've provided a fix to pyexcel-xlsx plugin. My fix worked with python 2. There was a problem with python 3  at the moment. But it only fails when the index will exceed "ABCDEFGHIJKLMN". I am still looking at it. Meanwhile, Would you like to try if your problem go away? You can install pyexcel-xlsx directly from git hub via the following command:

    pip install git+https://github.com/chfw/pyexcel-xlsx.git

**Comment by chfw** [comment]
Just let you know that my fix now worked in python 3.

**Comment by bigbagboom** [comment]
nice work! the issue is fixed. thank you!

**Comment by chfw** [comment]
Just a note, pyexcel-xlsx v0.0.3 is released to pypi, meaning pip install --upgrade pyexcel-xlsx would work.
