### ISSUE TITLE
numeric data with some user formated style in a xls file will lost

### ISSUE THREAD

**Issue by bigbagboom** [chfw/pyexcel#5]
ie:
a cell has a numeric value with formated stype "yyyy/m/d h:mm" in a xls file

like:
![image](https://cloud.githubusercontent.com/assets/1667227/5660357/51d0494e-975a-11e4-8f57-ae400cbedebb.png)

with following code and the data is lost:

import pyexcel as pe
import pyexcel.ext.xls # import it to be able handle xls file
import pyexcel.ext.xlsx # xlsx fi

book=pe.load('test3.xls')
book.save_as("test3.xlsx")

**Comment by chfw** [comment]
Yes, this is reproduced. I have provided a fix to pyexcel-xls plugin. Would you like to verify if the fix works for you? You can install it from github directly before I release it to pypi:

     pip install git+https://github.com/chfw/pyexcel-xls.git

Please let me know how it goes.

**Comment by bigbagboom** [comment]
nice work! the issue is fixed. thank you!

**Comment by chfw** [comment]
Just a note, pyexcel-xls v0.0.4 is released to pypi, meaning pip install --upgrade pyexcel-xls would work.
