### ISSUE TITLE
save_to_memory closes stream so you can't use it later

### ISSUE THREAD

**Issue by xgilest** [chfw/pyexcel#6]
>...
>output = StringIO()
>book = pe.Book({'hoja1':[['datos', 'de', 'prueba'],[1, 2, 3]], })
>book.save_to_memory('csv', output)
>logger.debug(output.getvalue())
This will raise an exception "I/O operation on closed file"

**Comment by chfw** [comment]
Thanks for reporting. 

I have added similar [test code](https://github.com/chfw/pyexcel/commit/1745e96782843442c8bb1075833153186356b520) to my tests but I failed to [reproduce the bug](https://travis-ci.org/chfw/pyexcel/builds/48399420). So, could you please share a bit more code that exposes the bug that you are having?

**Comment by xgilest** [comment]
I haven't had the time to prepare a reproduceable script with the bug, as soon as I can I'll send you. Thx

**Comment by chfw** [comment]
I am closing this error as no known way to reproduce the bug. Let's reopen this when it becomes reproducible
