### ISSUE TITLE
only one sheet left when i open and then save a multi-sheet file

### ISSUE THREAD

**Issue by bigbagboom** [chfw/pyexcel#7]
I have a 2 sheets excel file(no matter xls or xlsx). When I open it and then save it as a new file, only sheet 1 left in the new file.

Here is the code i use(i can provide the excel file if you need):

import pyexcel as pe
import pyexcel.ext.xls
import pyexcel.ext.xlsx 

book=pe.load('test6.xls')
for sheet in book:
    pass

book.save_as('test6rr.xls')  

book=pe.load('test6.xlsx')
for sheet in book:
    pass

book.save_as('test6rr.xlsx')

**Comment by bigbagboom** [comment]
actually the code will produce another issue which i believe the bug owe to openpyxl...

**Comment by chfw** [comment]
I think you would use 'load_book' instead of 'load'. I could have named 'load' as 'load_sheet' as I thought most of people would use single sheet for data processing. In this case, it is confusing.

**Comment by bigbagboom** [comment]
sorry, my mistake. you are right. i misused the method. it's all fine now. thank you for your clarification.
