### ISSUE TITLE
formula lost

### ISSUE THREAD

**Issue by bigbagboom** [chfw/pyexcel#8]
i have posted this issue on [bitbucket/openpyxl] (https://bitbucket.org/openpyxl/openpyxl/issue/413/formula-lost-in-cell) but the post was deemed invalid.

In pyexcel, there seems no data_only option in load_book(), so I can't read cell value with formula in some cells(not all the cells.)  In my case. the cell in first row with formula can be read but following rows are not.

**Comment by chfw** [comment]
Hi, I managed to reproduce the bug and am able to get you the value by passing data_only=True. Please get it from github and verify before I will release it to pypi:

    pip install git+https://github.com/chfw/pyexcel-xlsx.git

However, passing data_only = False, openpyxl shall return all formula as text but as you have seen, it is not happening.  So, that's outside the scope of pyexcel.

**Comment by bigbagboom** [comment]
Thank you chfw. I tested your code, Now with or without data_only option, all the values with formula can be returned correctly(as value, not formula string). I think it's ok, but it's your call to determine.

**Comment by chfw** [comment]
pyexcel-xlsx plugin has been released to pypi. Hence, I am closing this issue.
